package cool.android.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cool.weiboproject.android.bean.WeiBoBean;

import cool.android.greendao.WeiBoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig weiBoBeanDaoConfig;

    private final WeiBoBeanDao weiBoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        weiBoBeanDaoConfig = daoConfigMap.get(WeiBoBeanDao.class).clone();
        weiBoBeanDaoConfig.initIdentityScope(type);

        weiBoBeanDao = new WeiBoBeanDao(weiBoBeanDaoConfig, this);

        registerDao(WeiBoBean.class, weiBoBeanDao);
    }
    
    public void clear() {
        weiBoBeanDaoConfig.clearIdentityScope();
    }

    public WeiBoBeanDao getWeiBoBeanDao() {
        return weiBoBeanDao;
    }

}
